version: '3.7'
services:
  mysql:
    image: mysql:8.0.19
    restart: always
    ports:
      - '3308:3308'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - '5032:5032'
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'